let currentRole="guide";
let livekitRoom=null;
let isMuted=false;
let currentRoomCode=null;
let autoJoining=false;
const $=id=>document.getElementById(id);
const statusEl=$("status"),debugEl=$("debug"),shareToolsEl=$("shareTools"),listenerStatEl=$("listenerStat"),connectedToolsEl=$("connectedTools"),listenerCountEl=$("listenerCount"),muteBtn=$("muteBtn"),retryMicBtn=$("retryMicBtn"),leaveBtn=$("leaveBtn"),guideStartEl=$("guideStart"),listenerStartEl=$("listenerStart");
function setStatus(t,type="idle"){statusEl.textContent=t;statusEl.className="status "+type}
function showDebug(o){debugEl.textContent=typeof o==="string"?o:JSON.stringify(o,null,2);debugEl.classList.add("show")}
function clearDebug(){debugEl.classList.remove("show");debugEl.textContent=""}
function roomCode(){return Math.floor(1000+Math.random()*9000).toString()}
function randomIdentity(role){return (role==="guide"?"Guide":"Listener")+"-"+Math.floor(100000+Math.random()*900000)}
function buildJoinUrl(room){const u=new URL(window.location.href);u.searchParams.set("room",room);u.searchParams.set("role","listener");u.searchParams.set("autoJoin","1");return u.toString()}
function showShareQr(room,role){const url=buildJoinUrl(room);$("joinUrlText").textContent=url;$("qrImage").src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data="+encodeURIComponent(url);$("qrTitle").textContent=role==="guide"?"遊客掃碼加入":"分享給同行者掃碼加入";shareToolsEl.classList.remove("hidden")}
function updateListenerCount(){if(!livekitRoom||currentRole!=="guide")return;let c=0;livekitRoom.remoteParticipants.forEach(()=>c++);listenerCountEl.textContent=String(c)}
function setRole(role){currentRole=role;document.querySelectorAll(".mode").forEach(b=>b.classList.remove("active"));document.querySelector(`.mode[data-role="${role}"]`).classList.add("active");if(role==="guide"){guideStartEl.classList.remove("hidden");listenerStartEl.classList.add("hidden")}else{guideStartEl.classList.add("hidden");listenerStartEl.classList.remove("hidden")}}
async function requestGuideMicrophone(){if(!livekitRoom||currentRole!=="guide")return false;try{await livekitRoom.localParticipant.setMicrophoneEnabled(true);retryMicBtn.classList.add("hidden");muteBtn.classList.remove("hidden");isMuted=false;muteBtn.textContent="導遊靜音";setStatus("導遊模式已連線。麥克風已啟用。","ok");return true}catch(err){console.error(err);retryMicBtn.classList.remove("hidden");muteBtn.classList.add("hidden");setStatus("麥克風尚未允許。請按「重新允許麥克風」，或到瀏覽器網址列左側權限設定允許麥克風。","error");showDebug(err.message||String(err));return false}}
async function connectTour(room,role){clearDebug();if(!window.P104_CONFIG||!P104_CONFIG.LIVEKIT_URL||!P104_CONFIG.TOKEN_FUNCTION_URL){setStatus("請先建立 config.js，並填入 LIVEKIT_URL 與 TOKEN_FUNCTION_URL。","error");return}if(!/^[0-9]{4}$/.test(room)){setStatus("導覽連結或代碼不正確。","error");return}if(livekitRoom){try{await livekitRoom.disconnect()}catch(e){}livekitRoom=null}currentRoomCode=room;const identity=randomIdentity(role);setStatus("正在建立導覽連線...");const res=await fetch(P104_CONFIG.TOKEN_FUNCTION_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({room,identity,role})});const data=await res.json().catch(()=>({error:"Response is not JSON."}));if(!res.ok||!data.token){setStatus("無法取得 LiveKit token。請查看下方錯誤細節。","error");showDebug(data);return}livekitRoom=new LivekitClient.Room({adaptiveStream:true,dynacast:true});livekitRoom.on(LivekitClient.RoomEvent.TrackSubscribed,(track)=>{if(track.kind==="audio"){const audio=track.attach();audio.autoplay=true;document.body.appendChild(audio)}});livekitRoom.on(LivekitClient.RoomEvent.ParticipantConnected,updateListenerCount);livekitRoom.on(LivekitClient.RoomEvent.ParticipantDisconnected,updateListenerCount);livekitRoom.on(LivekitClient.RoomEvent.Disconnected,()=>{connectedToolsEl.classList.add("hidden");shareToolsEl.classList.add("hidden");listenerStatEl.classList.add("hidden");retryMicBtn.classList.add("hidden");setStatus("連線已中斷。","idle")});await livekitRoom.connect(P104_CONFIG.LIVEKIT_URL,data.token);connectedToolsEl.classList.remove("hidden");showShareQr(room,role);if(role==="guide"){listenerStatEl.classList.remove("hidden");updateListenerCount();await requestGuideMicrophone()}else{listenerStatEl.classList.add("hidden");muteBtn.classList.add("hidden");retryMicBtn.classList.add("hidden");setStatus("遊客模式已連線。正在收聽導覽。","ok")}}
async function createQrAndStartGuide(){const room=roomCode();currentRoomCode=room;showShareQr(room,"guide");setStatus("QRCode 已建立，正在啟動導遊麥克風...");await connectTour(room,"guide")}
async function manualJoinListener(){const room=$("room").value.trim();await connectTour(room,"listener")}
function applyUrlParams(){const p=new URLSearchParams(window.location.search);const room=p.get("room");const role=p.get("role");const autoJoin=p.get("autoJoin");if(role==="listener"){setRole("listener");if(room&&/^[0-9]{4}$/.test(room)){$("room").value=room;currentRoomCode=room;showShareQr(room,"listener");if(autoJoin==="1"&&!autoJoining){autoJoining=true;setTimeout(()=>connectTour(room,"listener"),300)}}}else{setRole("guide")}}
document.querySelectorAll(".mode").forEach(btn=>btn.addEventListener("click",()=>setRole(btn.dataset.role)));
$("createQrBtn").addEventListener("click",createQrAndStartGuide);
$("joinBtn").addEventListener("click",manualJoinListener);
muteBtn.addEventListener("click",async()=>{if(!livekitRoom||currentRole!=="guide")return;isMuted=!isMuted;try{await livekitRoom.localParticipant.setMicrophoneEnabled(!isMuted);muteBtn.textContent=isMuted?"取消靜音":"導遊靜音";setStatus(isMuted?"導遊模式已連線。麥克風目前靜音。":"導遊模式已連線。麥克風已啟用。","ok")}catch(err){retryMicBtn.classList.remove("hidden");muteBtn.classList.add("hidden");setStatus("麥克風操作失敗，請重新允許麥克風。","error");showDebug(err.message||String(err))}});
retryMicBtn.addEventListener("click",requestGuideMicrophone);
leaveBtn.addEventListener("click",async()=>{if(livekitRoom){await livekitRoom.disconnect();livekitRoom=null}connectedToolsEl.classList.add("hidden");shareToolsEl.classList.add("hidden");listenerStatEl.classList.add("hidden");retryMicBtn.classList.add("hidden");muteBtn.classList.remove("hidden");setStatus("已離開導覽。","idle")});
applyUrlParams();
